//
//  AuthEntities.swift
//  SharedNotes
//
//  Created by Sergey Petrachkov on 8/29/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//


import RealmSwift

class Note : Object {
  
}

class User : Object {
  dynamic var userId: String = ""
  dynamic var firstName: String = ""
  dynamic var lastName: String = ""
  var notes: List<Note> = List<Note>()
}
enum Auth
{
  // MARK: Use cases
  
  enum Context
  {
    struct Request {
      let firstname : String
      let lastname : String
    }
    struct Response {
      let user : User
      var id : String {
        return user.userId
      }
      var firstname : String {
        return user.firstName
      }
      var lastname : String {
        return user.lastName
      }
      
      init(user: User) {
        self.user = user
      }
    }
    struct ViewModel {
      
    }
  }
}
