//
//  AuthRouter.swift
//  SharedNotes
//
//  Created by Sergey Petrachkov on 8/29/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol AuthRoutingLogic {
  func showError(from view: UIViewController, with message : String)
  func showRegisteredModule(from view: UIViewController, for user: User)
}


class AuthRouter: AuthRoutingLogic {
  // MARK: - Routing
  func showError(from view: UIViewController, with message : String) {
    let alertController = UIAlertController(title: "Error!", message: message, preferredStyle: .alert)
    alertController.addAction(UIAlertAction(title: "Ok", style: .cancel, handler: nil))
    view.present(alertController, animated: true, completion: nil)
  }
  func showRegisteredModule(from view: UIViewController, for user: User) {
    let tabHost = TabHostAssembly.createModule(user: user)
    UIApplication.shared.delegate?.window??.rootViewController = tabHost
  }
//  func showSomething(from view: UIViewController, with routingParams : YourRoutingParams) {
//    let nextVC = NextViewController()
//    nextVC.setup(with: routingParams)
//    view.navigationController?.push(nextVC, animated: true)
//  }
}
