//
//  UserRouter.swift
//  SharedNotes
//
//  Created by Sergey Petrachkov on 8/29/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol UserRoutingLogic {
  func logOut()
}


class UserRouter: UserRoutingLogic {
  // MARK: Routing
  func logOut() {
    let authModule = AuthAssembly.createModule()
    UIApplication.shared.delegate?.window??.rootViewController = authModule
  }
}
