//
//  UserViewController.swift
//  SharedNotes
//
//  Created by Sergey Petrachkov on 8/29/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit
import Bond

class UserViewController: UIViewController {
  //MARK: - UI properties
  
  @IBOutlet weak var lastnameLabel: UILabel!
  @IBOutlet weak var firstnameLabel: UILabel!
  //MARK: - Essentials
  var presenter : UserPresenterInput?

  // MARK: Initializers
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: - Setup
  private func setup() {
    self.presenter = UserPresenter(view: self, output: self)
  }
  
  // MARK: - Lifecycle
  override func viewDidLoad() {
    super.viewDidLoad()
    self.presenter?.start()
  }
  @IBAction func logoutTouchedUpInsode(_ sender: Any) {
    self.presenter?.logOut()
  }
}
extension UserViewController : UserPresenterOutput {
  func didChangeState(viewModel : UserModule.Context.ViewModel){
    self.firstnameLabel.text = viewModel.formattedFirstname
    self.lastnameLabel.text = viewModel.formattedLastname
  }
}
