//
//  UserInteractor.swift
//  SharedNotes
//
//  Created by Sergey Petrachkov on 8/29/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit
import RealmSwift

protocol UserInteractorInput
{
  var output : UserInteractorOutput? { get set }
  func logout()
}

protocol UserInteractorOutput {
  func didWipeOut()
  func didFail(with error: Error)
}

protocol UserDataStore
{
  //var name: String { get set }
}

class UserInteractor: UserInteractorInput, UserDataStore
{
  let service: UserService = UserService()
  var output: UserInteractorOutput?
  
  // MARK: Do something
  func logout() {
    if let realm = try? Realm() {
      do{
        try realm.write {
          realm.deleteAll()
          self.output?.didWipeOut()
        }
      }
      catch{
        self.output?.didFail(with: NSError(domain: "sharednote", code: -1, userInfo: [NSLocalizedDescriptionKey: "Realm write failure"]))
      }
    }
    else{
      self.output?.didFail(with: NSError(domain: "sharednote", code: -1, userInfo: [NSLocalizedDescriptionKey: "Realm failure"]))
    }
  }
}
