//
//  UserEntities.swift
//  SharedNotes
//
//  Created by Sergey Petrachkov on 8/29/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

enum UserModule
{
  // MARK: Use cases
  
  enum Context
  {
    struct Request
    {
      let userId : String
    }
    struct Response
    {
    }
    struct ViewModel
    {
      let user : User
      
      var formattedFirstname : String {
        return "First name: \(self.user.firstName)"
      }
      var formattedLastname : String {
        return "Last name: \(self.user.lastName)"
      }
      init(user: User){
        self.user = user
      }
    }
  }
}
