//
//  TabHostViewController.swift
//  SharedNotes
//
//  Created by Sergey Petrachkov on 8/29/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

class TabHostViewController: UITabBarController {
  //MARK: - UI properties
  
  //MARK: - Essentials
  var presenter : TabHostPresenterInput?

  // MARK: Initializers
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: - Setup
  private func setup()
  {
    self.presenter = TabHostPresenter(view: self, output: self)
  }
  
  // MARK: - Lifecycle
  override func viewDidLoad()
  {
    super.viewDidLoad()
  }
}
extension TabHostViewController : TabHostPresenterOutput {
  func didChangeState(viewModel : TabHost.Something.ViewModel){
    
  }
}
