//
//  TabHostInteractor.swift
//  SharedNotes
//
//  Created by Sergey Petrachkov on 8/29/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol TabHostInteractorInput
{
  var output : TabHostInteractorOutput? { get set }
  func doSomething(request: TabHost.Something.Request)
}

protocol TabHostInteractorOutput {
  func didReceive(some data : Any)
  func didFail(with error: Error)
}

protocol TabHostDataStore
{
  //var name: String { get set }
}

class TabHostInteractor: TabHostInteractorInput, TabHostDataStore
{
  let service: TabHostService = TabHostService()
  var output: TabHostInteractorOutput?
  
  // MARK: Do something
  
  func doSomething(request: TabHost.Something.Request)
  {
    // Let's say we execute some async operation, then we want to be able to inform our output when the operation is finshed
    // self.service.requestSomeDataAsync(requestParams: params, 
    //                                          succes: {
    //                                            receivedData in
    //                                              self.output?.didReceive(some: receivedData)
    //                                          }),
    //                                          failure: {
    //                                            error in 
    //                                              NSLog("An error has occured while retrieving some data: \(error)")
    //                                              self.output?.didFail(error: error)
    //                                          })
    self.service.doSomeWork()
  }
}
